{
    'name': 'Foundation Tiago',
    'version': '1.0',
    'summary': 'Manages foundations, machines, services, and measurements.',
    'sequence': 10,
    'description': """Long description""",
    'category': 'Construction',
    'website': 'https://www.yourcompany.com',
    'images': [],
    'depends': [
        'base',
        'sale',
        'mail',
        'product',
    ],
    'data': [
        'security/ir.model.access.csv',
        # 'views/foundation_views.xml',
        'views/foundation_estacas_view.xml',
        'views/foundation_maquina_view.xml',
        'views/foundation_medicao_view.xml',
        'views/foundation_obra_service_view.xml',
        'views/foundation_obra_view.xml',
        'views/freports.xml',
        'views/foundation_actions.xml',
        'views/foundation_menus.xml',
        # 'views/reports.xml'  # Onde você define seus paperformats, se necessário
        # 'views/foundation_obra_service_views.xml',
        # 'views/foundation_estacas_views.xml',
        # 'views/foundation_medicao_views.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',  # This is the line you need to add
}
