{
    'name': 'Foundation Skills',
    'version': '16.0.1.0.0',
    'summary': 'Manages foundations, machines, services, and measurements.',
    'sequence': 10,
    'description': """Long defsfsdfsd scription""",
    'author': 'Brainess Company, Odoo Community Association (OCA)',
    'category': 'Construction',
    'website': 'https://www.brainesscompany.com',
    'images': [],
    'depends': [
        'base',
        'sale',
        'account',
        'mail',
        'sale_management',
        'stock',
        'product',
        'maintenance',
        'hr',
    ],
    'data': [
        'security/security.xml',
        'views/gfip.xml',
        'views/foundation_chamada_view.xml',
        'views/chamada2.xml',
        'views/foundation_maquina_view.xml',
        'views/foundation_obra_view.xml',
        'views/foundation_medicao_view.xml',
        'views/foundation_obra_service_simples_view.xml',
        'views/foundation_estacas_view.xml',
        'views/foundation_relatorios_lista_view.xml',
        'views/foundation_relatorios_without_signature.xml',
        'views/foundation_maquina_registro_estacas.xml',
        'views/foundation_employee_assignment_views.xml',
        'views/foundation_faltas.xml',
        'views/foundation_menus.xml',
        'views/foundation_actions.xml',
        'views/sale_order_obra_extension.xml',
        'views/product_template.xml',
        'data/foundation_cron.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
